name: ipubook1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.2
  hexcolor: ^2.0.5
  firebase_auth: ^3.3.5
  font_awesome_flutter: ^9.0.0
  awesome_dialog: ^2.1.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.11.0
  http: ^0.13.4
  cloud_firestore: ^3.1.6
  simple_animations: ^4.0.1
  shared_preferences: ^2.0.13
  get: ^4.6.1
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.0.5
  google_maps_flutter: ^2.1.5
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  google_sign_in: '^4.5.1'
  location: ^4.2.0
  custom_info_window: ^1.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logolib.png"


  #provider:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/logo1.png
  android_gravity: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/first.jpg
    - assets/image/categoryBook/1.jpg
    - assets/image/categoryBook/2.png
    - assets/image/categoryBook/3.jpg
    - assets/image/categoryBook/4.jpg
    - assets/image/categoryBook/5.jpg
    - assets/image/categoryBook/6.png
    - assets/image/categoryBook/7.jpg
    - assets/image/categoryBook/8.jpg
    - assets/image/categoryBook/9.jpg
    - assets/image/categoryBook/10.jpg
    - assets/image/Book/1.jpg
    - assets/image/Book/2.jpg
    - assets/image/Book/3.jpg
    - assets/image/Book/4.jpg
    - assets/image/Book/5.jpg
    - assets/image/Book/6.jpg
    - assets/image/Book/7.jpg
    - assets/image/Book/8.jpg
    - assets/image/Book/9.jpg
    - assets/image/Book/10.jpg
    - assets/image/Book/11.jpg
    - assets/image/Book/12.jpg
    - assets/image/Book/13.jpg
    - assets/image/Book/14.jpg
    - assets/image/Book/15.jpg
    - assets/image/Book/16.jpg
    - assets/image/Book/17.jpg
    - assets/image/Book/18.jpg
    - assets/image/Book/19.jpg
    - assets/image/Book/20.jpg
    - assets/image/Book/21.jpg
    - assets/image/Book/22.jpg
    - assets/image/Book/23.jpg
    - assets/image/Book/24.jpg
    - assets/image/Book/25.jpg
    - assets/image/Book/26.jpg
    - assets/image/Book/27.jpg
    - assets/image/Book/28.jpg
    - assets/image/Book/29.jpg
    - assets/image/Book/30.jpg
    - assets/image/Book/31.jpg
    - assets/image/Book/32.jpg
    - assets/image/Book/33.jpg
    - assets/image/Book/34.jpg
    - assets/image/Book/35.jpg
    - assets/image/Book/36.jpg
    - assets/image/Book/37.jpg
    - assets/image/Book/38.jpg
    - assets/image/Book/39.jpg
    - assets/image/Book/40.jpg
    - assets/image/Book/41.jpg
    - assets/image/Book/42.jpg
    - assets/image/Book/43.jpg
    - assets/image/Book/44.jpg
    - assets/image/Book/45.jpg
    - assets/image/Book/46.jpg
    - assets/image/Book/47.jpg
    - assets/image/categoryTools/1.jpg
    - assets/image/categoryTools/2.jpg
    - assets/image/categoryTools/3.jpg
    - assets/image/categoryTools/4.jpg
    - assets/image/categoryTools/5.jpg
    - assets/image/categoryTools/6.jpg
    - assets/image/categoryTools/7.jpg
    - assets/image/Tools/1.png
    - assets/image/Tools/2.png
    - assets/image/Tools/3.png
    - assets/image/Tools/4.png
    - assets/image/Tools/5.png
    - assets/image/Tools/6.png
    - assets/image/Tools/7.png
    - assets/image/Tools/8.jpg
    - assets/image/Tools/9.png
    - assets/image/Tools/10.png
    - assets/image/Tools/11.png
    - assets/image/Tools/12.png
    - assets/image/Tools/13.png
    - assets/image/Tools/14.png
    - assets/image/Tools/15.png
    - assets/image/Tools/16.png
    - assets/image/Tools/17.png
    - assets/image/Tools/18.png
    - assets/image/Tools/19.png
    - assets/image/Tools/20.png
    - assets/image/Tools/21.png
    - assets/image/Tools/22.png
    - assets/image/Tools/23.png
    - assets/image/Tools/24.png
    - assets/image/Tools/25.png
    - assets/image/Tools/26.png
    - assets/image/Tools/27.png
    - assets/image/Tools/28.png
    - assets/image/Tools/29.jpg
    - assets/image/Tools/30.png
    - assets/image/Tools/31.png
    - assets/image/Tools/32.png
    - assets/image/Tools/33.png
    - assets/image/Tools/34.png
    - assets/image/Tools/35.png
    - assets/image/Tools/36.png
    - assets/image/Tools/37.png
    - assets/image/backGround.jpg
    - assets/image/appBar.jpg
    - assets/image/appBar1.jpg
    - assets/image/drawer.jpg
    - assets/image/drawer1.jpg
    - assets/image/logo.jpg
    - assets/image/logo1.png
    - assets/image/main_bottom.png
    - assets/image/main_top.png
    - assets/image/logo.png
    - assets/image/logolib.png
    - assets/image/bitmap.png
    - assets/image/google.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-light.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
