import "package:flutter/material.dart";
import 'models/books.dart';
import 'models/categories.dart';

List<Category> Book_CATEGORIES = [
  Category(
      id: 'c1',
      title: 'تقنية',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/1.jpg'),
  Category(
      id: 'c2',
      title: 'العمارة',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/2.png'),
  Category(
      id: 'c3',
      title: 'القانون',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/3.jpg'),
  Category(
      id: 'c4',
      title: 'الإسلامية',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/4.jpg'),
  Category(
      id: 'c5',
      title: 'الادب والشعر',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/5.jpg'),
  Category(
      id: 'c6',
      title: 'روايات',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/6.png'),
  Category(
      id: 'c7',
      title: 'الإدارة والأعمال',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/7.jpg'),
  Category(
      id: 'c8',
      title: 'الإشغال اليدوي',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/8.jpg'),
  Category(
      id: 'c9',
      title: 'الطبخ',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/9.jpg'),
  Category(
      id: 'c10',
      title: 'أطفال',
      color: Colors.white70,
      imageUrl: 'assets/image/categoryBook/10.jpg'),
];

List<Book> Books_Data = [
  Book(
    id: 'b1',
    categories: [
      'c1',
    ],
    title: 'الوصايا العشر في الامن السيبراني',
    writer: 'محمد شاكر المبيض',
    price: 5500,
    imageUrl: 'assets/image/Book/1.jpg',
    page: 64,
  ),
  Book(
    id: 'b2',
    categories: [
      'c1',
    ],
    title: 'مقدمة في الحاسب والانترنت ',
    writer: 'عبد الله عبد العزيز موسى',
    price: 3000,
    imageUrl: 'assets/image/Book/2.jpg',
    page: 320,
  ),
  Book(
    id: 'b3',
    categories: [
      'c1',
    ],
    title: 'استخدام نماذج الذكاء الاصطناعي في تطبيقات ادارة المعرفة ',
    writer: 'ماجد محمد أبو شرحة',
    price: 7000,
    imageUrl: 'assets/image/Book/3.jpg',
    page: 250,
  ),
  Book(
    id: 'b4',
    categories: [
      'c1',
    ],
    title: 'مهارات الحاسب الالي',
    writer: 'مركز الخوارزمي',
    price: 1500,
    imageUrl: 'assets/image/Book/4.jpg',
    page: 115,
  ),
  Book(
    id: 'b5',
    categories: ['c2'],
    title: 'الخطط اللونية في التصميم الداخلي وسيكولوجية اللون',
    writer: 'حنان القاصد',
    price: 4000,
    imageUrl: 'assets/image/Book/5.jpg',
    page: 190,
  ),
  Book(
    id: 'b6',
    categories: [
      'c2',
    ],
    title: 'عناصر التصميم والبناء',
    writer: 'أرنست روفر',
    price: 4500,
    imageUrl: 'assets/image/Book/6.jpg',
    page: 450,
  ),
  Book(
    id: 'b7',
    categories: [
      'c2',
    ],
    title: 'ثقافة البناء وجماليات العمارة',
    writer: 'أحمد عثمان',
    price: 7500,
    imageUrl: 'assets/image/Book/7.jpg',
    page: 330,
  ),
  Book(
    id: 'b8',
    categories: [
      'c2',
    ],
    title: 'الطرز المعمارية الإيطالية',
    writer: 'حسين محمد صالح',
    price: 15000,
    imageUrl: 'assets/image/Book/8.jpg',
    page: 400,
  ),
  Book(
    id: 'b9',
    categories: [
      'c2',
    ],
    title: 'القباب الإسلامية ',
    writer: 'مجموعة عمارة فوق العادة',
    price: 6000,
    imageUrl: 'assets/image/Book/9.jpg',
    page: 410,
  ),
  Book(
    id: 'b10',
    categories: [
      'c3',
    ],
    title: 'رسالة المحاماة',
    writer: 'رجائي عطية',
    price: 2000,
    imageUrl: 'assets/image/Book/10.jpg',
    page: 100,
  ),
  Book(
    id: 'b11',
    categories: [
      'c3',
    ],
    title: 'أساسيات عالم الدبلوماسية والقانون الدولي العام',
    writer: 'فيصل عبد العزيز',
    price: 3000,
    imageUrl: 'assets/image/Book/11.jpg',
    page: 135,
  ),
  Book(
    id: 'b12',
    categories: [
      'c3',
    ],
    title: 'المدخل لدراسة العلوم القانونية',
    writer: 'رزق الريس/خالد الرويس',
    price: 12000,
    imageUrl: 'assets/image/Book/12.jpg',
    page: 360,
  ),
  Book(
    id: 'b13',
    categories: [
      'c3',
    ],
    title: 'منهاج العارفين في تدريب المحامين',
    writer: 'سامي عبد الوهاب',
    price: 2000,
    imageUrl: 'assets/image/Book/13.jpg',
    page: 150,
  ),
  Book(
    id: 'b14',
    categories: [
      'c4',
    ],
    title: 'الاسلام والايمان منظومة القيم',
    writer: 'محمد الشحرور',
    price: 5000,
    imageUrl: 'assets/image/Book/14.jpg',
    page: 330,
  ),
  Book(
    id: 'b15',
    categories: [
      'c4',
    ],
    title: 'الاسلام والانسان من نتائج القراءة المعاصرة',
    writer: 'محمد الشحرور',
    price: 6000,
    imageUrl: 'assets/image/Book/15.jpg',
    page: 450,
  ),
  Book(
    id: 'b16',
    categories: [
      'c4',
    ],
    title: 'الفضاء المقدس في الاسلام الى نهاية القرن 14 ميلادي',
    writer: 'فوزية الغالي',
    price: 3000,
    imageUrl: 'assets/image/Book/16.jpg',
    page: 250,
  ),
  Book(
    id: 'b17',
    categories: [
      'c4',
    ],
    title: 'كيف نساعد أطفالنا على صيام رمضان؟',
    writer: 'دار الطويق للنشر',
    price: 1500,
    imageUrl: 'assets/image/Book/17.jpg',
    page: 50,
  ),
  Book(
    id: 'b18',
    categories: [
      'c5',
    ],
    title: 'خلجات العمر الى عينيها',
    writer: 'عرفان نظام الدين',
    price: 3000,
    imageUrl: 'assets/image/Book/18.jpg',
    page: 190,
  ),
  Book(
    id: 'b19',
    categories: [
      'c5',
    ],
    title: 'سكنت فؤاد نور',
    writer: 'نور أيمن قاسم',
    price: 4500,
    imageUrl: 'assets/image/Book/19.jpg',
    page: 244,
  ),
  Book(
    id: 'b20',
    categories: [
      'c5',
    ],
    title: 'أضيئي كالنجمة',
    writer: 'فاطمة الحمدان',
    price: 1000,
    imageUrl: 'assets/image/Book/20.jpg',
    page: 60,
  ),
  Book(
    id: 'b21',
    categories: [
      'c5',
    ],
    title: 'الحوار في الرواية العربية',
    writer: 'زهير القاسمي',
    price: 4500,
    imageUrl: 'assets/image/Book/21.jpg',
    page: 175,
  ),
  Book(
    id: 'b22',
    categories: [
      'c5',
    ],
    title: 'اشكالية التجنيس في القص الهزلي العربي القديم',
    writer: 'منصف الربعاوي',
    price: 10000,
    imageUrl: 'assets/image/Book/22.jpg',
    page: 560,
  ),
  Book(
    id: 'b23',
    categories: [
      'c6',
    ],
    title: 'شاطىء المحار',
    writer: 'ماري هيرمانسون',
    price: 1200,
    imageUrl: 'assets/image/Book/23.jpg',
    page: 75,
  ),
  Book(
    id: 'b24',
    categories: [
      'c6',
    ],
    title: 'أطلس الحنين المستحيل',
    writer: 'أنورادا روي',
    price: 4800,
    imageUrl: 'assets/image/Book/24.jpg',
    page: 233,
  ),
  Book(
    id: 'b25',
    categories: [
      'c6',
    ],
    title: 'حياة',
    writer: 'دايفد فاغنر',
    price: 1500,
    imageUrl: 'assets/image/Book/25.jpg',
    page: 200,
  ),
  Book(
    id: 'b26',
    categories: [
      'c6',
    ],
    title: 'شمشون وتفاحة',
    writer: 'أمير تاج السر',
    price: 1000,
    imageUrl: 'assets/image/Book/26.jpg',
    page: 90,
  ),
  Book(
    id: 'b27',
    categories: [
      'c6',
    ],
    title: 'أحلام الحياة في الشمال',
    writer: 'برهان سونميز',
    price: 3500,
    imageUrl: 'assets/image/Book/27.jpg',
    page: 266,
  ),
  Book(
    id: 'b28',
    categories: [
      'c6',
    ],
    title: 'عين وردة',
    writer: 'جبور الدويهي',
    price: 4000,
    imageUrl: 'assets/image/Book/28.jpg',
    page: 370,
  ),
  Book(
    id: 'b29',
    categories: [
      'c7',
    ],
    title: 'التسويق الناجح أسرار واستراتيجيات',
    writer: 'روندا أبرامز',
    price: 6000,
    imageUrl: 'assets/image/Book/29.jpg',
    page: 257,
  ),
  Book(
    id: 'b30',
    categories: [
      'c7',
    ],
    title: 'فكر خطأ',
    writer: 'مايك بيرن',
    price: 2500,
    imageUrl: 'assets/image/Book/30.jpg',
    page: 180,
  ),
  Book(
    id: 'b31',
    categories: [
      'c7',
    ],
    title: 'مقدمة في ريادة الاعمال والمنشآت الصغيرة ومتوسطة الحجم',
    writer: 'نعيمة فهد',
    price: 13000,
    imageUrl: 'assets/image/Book/31.jpg',
    page: 360,
  ),
  Book(
    id: 'b32',
    categories: [
      'c7',
    ],
    title: 'التسويق برؤية خبير',
    writer: 'وليد عبد الله الشلهوب',
    price: 1000,
    imageUrl: 'assets/image/Book/32.jpg',
    page: 85,
  ),
  Book(
    id: 'b33',
    categories: [
      'c7',
    ],
    title: 'من جيد الى عظيم',
    writer: 'جيم كولنز',
    price: 7800,
    imageUrl: 'assets/image/Book/33.jpg',
    page: 410,
  ),
  Book(
    id: 'b34',
    categories: [
      'c8',
    ],
    title: 'المدرب الاول في التفصيل والخياطة',
    writer: 'عبد الله عيسى',
    price: 5500,
    imageUrl: 'assets/image/Book/34.jpg',
    page: 550,
  ),
  Book(
    id: 'b35',
    categories: [
      'c8',
    ],
    title: 'تصميمات عربية كتاب تلوين',
    writer: 'مكتبة جرير',
    price: 5000,
    imageUrl: 'assets/image/Book/35.jpg',
    page: 279,
  ),
  Book(
    id: 'b36',
    categories: [
      'c8',
    ],
    title: '       سحر الترتيب الفن الياباني في التنظيم',
    writer: 'ماري كوندو',
    price: 6500,
    imageUrl: 'assets/image/Book/36.jpg',
    page: 246,
  ),
  Book(
    id: 'b37',
    categories: [
      'c8',
    ],
    title: 'فن المانجا',
    writer: 'سماح هاشم',
    price: 1000,
    imageUrl: 'assets/image/Book/37.jpg',
    page: 50,
  ),
  Book(
    id: 'b38',
    categories: [
      'c8',
    ],
    title: 'فن الخياطة خطوة خطوة',
    writer: 'ناديا دياب',
    price: 2500,
    imageUrl: 'assets/image/Book/38.jpg',
    page: 315,
  ),
  Book(
    id: 'b39',
    categories: [
      'c9',
    ],
    title: 'مطبخ لين',
    writer: 'لين عبد العزيز',
    price: 3000,
    imageUrl: 'assets/image/Book/39.jpg',
    page: 375,
  ),
  Book(
    id: 'b40',
    categories: [
      'c9',
    ],
    title: 'أطباق النخبة',
    writer: 'أمل يحيى',
    price: 2000,
    imageUrl: 'assets/image/Book/40.jpg',
    page: 146,
  ),
  Book(
    id: 'b41',
    categories: [
      'c9',
    ],
    title: 'مذاق العلا',
    writer: 'معهد فيراندي باريس',
    price: 25000,
    imageUrl: 'assets/image/Book/41.jpg',
    page: 620,
  ),
  Book(
    id: 'b42',
    categories: [
      'c9',
    ],
    title: 'فطائر الوافل والكريب',
    writer: 'مكتبة جرير',
    price: 5500,
    imageUrl: 'assets/image/Book/42.jpg',
    page: 189,
  ),
  Book(
    id: 'b43',
    categories: [
      'c10',
    ],
    title: 'الأمير الصغير',
    writer: 'أنطوان دو سانت',
    price: 1200,
    imageUrl: 'assets/image/Book/43.jpg',
    page: 48,
  ),
  Book(
    id: 'b44',
    categories: [
      'c10',
    ],
    title: 'من حكايا الكيبيك',
    writer: 'جون موزي',
    price: 1000,
    imageUrl: 'assets/image/Book/44.jpg',
    page: 57,
  ),
  Book(
    id: 'b45',
    categories: [
      'c10',
    ],
    title: 'من حكايا البحر الابيض المتوسط ',
    writer: 'جون موزي',
    price: 1000,
    imageUrl: 'assets/image/Book/45.jpg',
    page: 54,
  ),
  Book(
    id: 'b46',
    categories: [
      'c10',
    ],
    title: 'حكايات جحا',
    writer: 'مكتبة جرير',
    price: 7000,
    imageUrl: 'assets/image/Book/46.jpg',
    page: 288,
  ),
  Book(
    id: 'b47',
    categories: [
      'c10',
    ],
    title: 'حان وقت العمل الجماعي',
    writer: 'مكتبة جرير',
    price: 7500,
    imageUrl: 'assets/image/Book/47.jpg',
    page: 400,
  ),
];
